import { FormData } from "./FormData";

const DefaultData: FormData = {
  currentRole: { label: "default", value: "Black Women Physician Member" },
  firstName: "",
  lastName: "",
  middleInitial: "",
  suffix: "",
  email: "",
  emailSecondary: "",
  phone: "",
  street: "",
  city: "",
  state: "",
  zipcode: "",
  country: "",
  address: "",
  race: [],
  ethnicity: [],
  gender: "",
  pronouns: "",
  academicAffiliation: { label: "default", value: "N/A Not Applicable" },
  hospitalOrcompany: "",
  position: "",
  specialty: { label: "default", value: "N/A Not Applicable" },
  expertise: [],
  region: { label: "default", value: "(United States)" },
  startChapter: "",
  includeInDirectory: "",
  includeResume: "",
  includeInResumeBank: "",
  memberOfDivaDocsBoston: "",
  wantToMentor: "",
  wantToSponsor: "",
};

export default DefaultData;
